#!/usr/bin/perl

# FIXME where to get squidguard_conf from?
# probably default location for perl modules?
BEGIN {
    push @INC, '/usr/share/YaST2/modules/';
}

use ycp;
use strict;
use squidguard_conf;

while ( <STDIN> )
{
    my ($command, $path, $argument) = ycp::ParseCommand ($_);

    #----------------------------------------------------------
    #  Expected calls:
    #  Read(.squidguard, file_name)
    #	-> returns the configuration map
    #----------------------------------------------------------

    if ( $command eq "Read" )
    {
	y2internal ("path $path, command $command, arg $argument");
	if ( $path eq '.' ) {

	    my $config	= squidguard_conf->ReadSquidGuardConf ($argument);
	    ycp::Return ($config);
	}
	else {
	    y2error ("wrong path ($path) or argument: ", ref ($argument));
	    ycp::Return("wrong path or argument");
	}
    }
    elsif ($command eq "result")
    {
	exit;
    }
    else
    {
	y2error ("wrong command ($command), only Read is accepted");
	ycp::Return("wrong command, only Read is accepted");
    }
}

# end
